"""Data models for the Exam Prep Bot."""

from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any
from enum import Enum


class QueryType(str, Enum):
    """Intent types for queries."""
    DEFINITION = "definition"
    EXPLAIN = "explain"
    COMPARE = "compare"
    PROCESS = "process"
    VAGUE = "vague"
    EXAMPLE = "example"
    DIAGRAM = "diagram"
    HOMEWORK = "homework"


class ChunkMetadata(BaseModel):
    """Metadata for document chunks."""
    page_number: int
    section_title: Optional[str] = None
    section_level: Optional[int] = None  # 1, 2, 3 for h1, h2, h3
    chunk_index: int
    total_chunks: int
    file_name: str
    chunk_position: str = Field(default="unknown")  # beginning, middle, end
    


class DocumentChunk(BaseModel):
    """A chunk of text from a document."""
    content: str
    metadata: ChunkMetadata
    embedding: Optional[List[float]] = None
    
    class Config:
        arbitrary_types_allowed = True


class Document(BaseModel):
    """Uploaded document with metadata."""
    file_name: str
    file_type: str  # "pdf" or "docx"
    file_size_bytes: int
    total_chunks: int
    chunks: List[DocumentChunk]
    upload_timestamp: str
    
    class Config:
        arbitrary_types_allowed = True


class RetrievedChunk(BaseModel):
    """Retrieved chunk with relevance score."""
    content: str
    metadata: ChunkMetadata
    relevance_score: float = Field(ge=0.0, le=1.0)
    rank: int
    
    class Config:
        arbitrary_types_allowed = True


class IntentClassificationResult(BaseModel):
    """Result of intent classification."""
    query: str
    primary_intent: QueryType
    confidence: float = Field(ge=0.0, le=1.0)
    alternative_intents: Optional[Dict[QueryType, float]] = None
    reasoning: Optional[str] = None


class SourceCitation(BaseModel):
    """Source citation for an answer."""
    page_number: int
    section_title: Optional[str] = None
    quoted_text: str
    confidence: float = Field(ge=0.0, le=1.0)
    relevance_score: float = Field(ge=0.0, le=1.0)


class GeneratedAnswer(BaseModel):
    """Answer generated by Claude."""
    content: str
    reasoning: Optional[str] = None
    claims: Optional[List[str]] = None


class AnswerWithSources(BaseModel):
    """Complete answer with sources."""
    answer: str
    query_intent: QueryType
    intent_confidence: float = Field(ge=0.0, le=1.0)
    sources: List[SourceCitation]
    overall_confidence: float = Field(ge=0.0, le=1.0)
    hallucination_risk: str = Field(default="low")  # low, medium, high
    response_time_seconds: float
    format_type: str  # "definition", "comparison_table", "ordered_steps", etc.


class QueryContext(BaseModel):
    """Context for processing a query."""
    query: str
    document_id: str
    retrieved_chunks: List[RetrievedChunk]
    intent: QueryType
    intent_confidence: float
    in_scope: bool
    relevance_score: float


class EvaluationMetrics(BaseModel):
    """Evaluation metrics for a single query."""
    query: str
    intent_type: QueryType
    predicted_answer: str
    ground_truth: Optional[str] = None
    accuracy_score: Optional[float] = None  # 0-1
    citation_accuracy: Optional[float] = None  # 0-1
    hallucination_detected: Optional[bool] = None
    response_time: float
    intent_classification_correct: bool


class BatchEvaluationResult(BaseModel):
    """Results from batch evaluation."""
    total_queries: int
    correct_predictions: int
    accuracy: float
    avg_response_time: float
    per_intent_accuracy: Dict[QueryType, float]
    hallucination_rate: float
    citation_accuracy: float
    metrics: List[EvaluationMetrics]


class ChatMessage(BaseModel):
    """A message in the chat history."""
    role: str  # "user" or "assistant"
    content: str
    timestamp: str
    intent_type: Optional[QueryType] = None
    metadata: Optional[Dict[str, Any]] = None


class ChatSession(BaseModel):
    """A chat session with history."""
    session_id: str
    document_id: str
    messages: List[ChatMessage]
    created_at: str
    updated_at: str
    total_queries: int


class APIResponse(BaseModel):
    """Standard API response format."""
    success: bool
    data: Optional[Dict[str, Any]] = None
    error: Optional[str] = None
    error_code: Optional[str] = None
    timestamp: str
