"""add chat_session title and device_id

Revision ID: 2dccc8a1f14f
Revises: 6c9e6ceb7d23
Create Date: 2026-07-29 17:01:05.563227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dccc8a1f14f'
down_revision: Union[str, Sequence[str], None] = '6c9e6ceb7d23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('device_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('title', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_chat_sessions_device_id'), ['device_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_sessions_device_id'))
        batch_op.drop_column('title')
        batch_op.drop_column('device_id')

    # ### end Alembic commands ###
