"""add conversation memory and session summarization fields

Revision ID: 6c9e6ceb7d23
Revises: be686e75be04
Create Date: 2026-07-29 11:18:30.259701

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6c9e6ceb7d23"
down_revision: Union[str, Sequence[str], None] = "be686e75be04"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conversation_memories",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=True),
        sa.Column("summary_text", sa.Text(), nullable=False),
        sa.Column("covers_from_message_id", sa.Integer(), nullable=False),
        sa.Column("covers_to_message_id", sa.Integer(), nullable=False),
        sa.Column("embedded", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["covers_from_message_id"],
            ["chat_messages.id"],
        ),
        sa.ForeignKeyConstraint(
            ["covers_to_message_id"],
            ["chat_messages.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["chat_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("chat_messages", schema=None) as batch_op:
        batch_op.add_column(sa.Column("token_count", sa.Integer(), nullable=True))

    with op.batch_alter_table("chat_sessions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.String(length=36), nullable=True))
        # server_default so pre-existing rows get a valid value — the ORM's
        # default=0 only applies to new inserts, not this ALTER TABLE.
        batch_op.add_column(sa.Column("turn_count", sa.Integer(), nullable=False, server_default="0"))
        batch_op.add_column(sa.Column("last_summarized_message_id", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("chat_sessions", schema=None) as batch_op:
        batch_op.drop_column("last_summarized_message_id")
        batch_op.drop_column("turn_count")
        batch_op.drop_column("user_id")

    with op.batch_alter_table("chat_messages", schema=None) as batch_op:
        batch_op.drop_column("token_count")

    op.drop_table("conversation_memories")
    # ### end Alembic commands ###
