"""add missing indexes on chat_messages.session_id and conversation_memories.session_id

Revision ID: d4b78d36f5b3
Revises: a106cd3ff026
Create Date: 2026-07-31 10:13:29.931702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4b78d36f5b3'
down_revision: Union[str, Sequence[str], None] = 'a106cd3ff026'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_messages_session_id'), ['session_id'], unique=False)

    with op.batch_alter_table('conversation_memories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversation_memories_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation_memories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_memories_session_id'))

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_messages_session_id'))

    # ### end Alembic commands ###
